application: c2dmsend
version: 1
runtime: python
api_version: 1

handlers:

- url: /static
  static_dir: static

- url: /api/1/send
  script: main.py

- url: /dashboard
  login: required
  script: main.py

- url: /
  script: main.py
